services:
  miner-vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    command: >
      --model NousResearch/Hermes-3-Llama-3.1-8B
      --return-tokens-as-token-ids 
      --served-model-name NousResearch/Hermes-3-Llama-3.1-8B
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
    ports:
      - 8000:8000
    ipc: host
    volumes:
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "1"
              capabilities: [gpu]
volumes:
  hf_cache:
