services:
  miner-vllm:
    image: manifoldlabs/vllm-openai:latest
    runtime: nvidia
    command: --model NousResearch/Meta-Llama-3.1-8B-Instruct --return-tokens-as-token-ids --served-model-name NousResearch/Meta-Llama-3.1-8B-Instruct
    ports:
      - 8000:8000
    ipc: host
    volumes:
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "1"
              capabilities: [gpu]
volumes:
  hf_cache:
