version: 1
formatters:
  json:
    (): "logconfig.CustomJsonFormatter"
    format: "%(created)s %(levelname)s %(message)s"
    rename_fields: {"created": "ts", "message": "msg", "levelname": "level"}
handlers:
  main:
    class: logging.StreamHandler
    level: INFO
    formatter: json
loggers:
  main:
    level: INFO
    handlers: [main]
    qualname: main
